sources:
    - name: cini
      description: Contains the data of pre and post survey for partner cini. Also contains the survey dictionary to decode the data
      schema: staging
      tables:
          - name: pre_post_answers
            identifier: CINI_ShortV2_Yr1_2022
            description: Survey responses
    - name: sru
      description: Contains the data of pre and post survey for partner sru. Also contains the survey dictionary to decode the data
      schema: staging
      tables:
          - name: pre_post_answers
            identifier: SRU_ShortV2_Yr1_2021-22
            description: Survey responses
    - name: general
      description: Contains the survey dictionary to decode the data
      schema: staging
      tables:
          - name: survey_dictionary
            identifier: survey_dictionary
            description: Survey dictionary